import { describe, it, expect, vi, beforeEach } from 'vitest';

// Shared spies for the mocked OpenAI client. Declared via vi.hoisted so they
// exist before vi.mock (which is hoisted to the top of the module) runs.
const mocks = vi.hoisted(() => ({
    create: vi.fn(),
    get: vi.fn(),
    post: vi.fn(),
    ctor: vi.fn(),
}));

vi.mock('openai', () => ({
    default: vi.fn(function (opts: unknown) {
        mocks.ctor(opts);
        return {
            completions: { create: mocks.create },
            get: mocks.get,
            post: mocks.post,
        };
    }),
}));

import { Reviewer } from '../src/index';

const okText = (text: string) => ({ choices: [{ text }] });

beforeEach(() => {
    vi.clearAllMocks();
});

describe('Reviewer constructor', () => {
    it('passes the api key to the OpenAI client', () => {
        new Reviewer('sk-test-123');
        expect(mocks.ctor).toHaveBeenCalledWith({ apiKey: 'sk-test-123' });
    });

    it('applies default model and maxTokens', async () => {
        mocks.create.mockResolvedValue(okText('ok'));
        await new Reviewer('sk-test').submitCode('code');

        expect(mocks.create).toHaveBeenCalledWith(
            expect.objectContaining({ model: 'gpt-3.5-turbo-instruct', max_tokens: 400 }),
        );
    });

    it('honours custom model and maxTokens', async () => {
        mocks.create.mockResolvedValue(okText('ok'));
        await new Reviewer('sk-test', 'custom-model', 99).submitCode('code');

        expect(mocks.create).toHaveBeenCalledWith(
            expect.objectContaining({ model: 'custom-model', max_tokens: 99 }),
        );
    });
});

describe('submitCode (regression: uses completions.create, not the removed /engines endpoint)', () => {
    it('calls completions.create and never the legacy post(/engines) route', async () => {
        mocks.create.mockResolvedValue(okText('great code'));
        const result = await new Reviewer('sk-test').submitCode('const a = 1;');

        expect(result).toBe('great code');
        expect(mocks.create).toHaveBeenCalledTimes(1);
        expect(mocks.post).not.toHaveBeenCalled();
        expect(mocks.create.mock.calls[0][0].prompt).toContain('const a = 1;');
    });
});

describe('generateDocumentation wrapping logic', () => {
    it('wraps bare text in a JSDoc block', async () => {
        mocks.create.mockResolvedValue(okText('Adds two numbers.'));
        const doc = await new Reviewer('sk-test').generateDocumentation('code');

        expect(doc.startsWith('/**')).toBe(true);
        expect(doc.endsWith('*/')).toBe(true);
        expect(doc).toContain('Adds two numbers.');
    });

    it('leaves already-formatted JSDoc untouched', async () => {
        const formatted = '/**\n * done\n */';
        mocks.create.mockResolvedValue(okText(formatted));
        const doc = await new Reviewer('sk-test').generateDocumentation('code');

        expect(doc).toBe(formatted);
    });

    it('returns a fallback message when there are no choices', async () => {
        mocks.create.mockResolvedValue({ choices: [] });
        const doc = await new Reviewer('sk-test').generateDocumentation('code');

        expect(doc).toBe('No documentation generated by OpenAI API');
    });
});

describe('getCurrentModels', () => {
    it('returns the data array from the models endpoint', async () => {
        const models = [{ id: 'gpt-4', object: 'model', created: 1, owned_by: 'openai' }];
        mocks.get.mockResolvedValue({ data: models });

        const result = await new Reviewer('sk-test').getCurrentModels();
        expect(result).toEqual(models);
        expect(mocks.get).toHaveBeenCalledWith('/models');
    });
});

describe('completion-based methods return the model text', () => {
    const methods = [
        'submitCodeAssistanceMode',
        'optimizeCode',
        'generateTests',
        'securityAnalysis',
        'codeStyleRecommendations',
        'historicalAnalysis',
    ] as const;

    for (const method of methods) {
        it(`${method} returns choices[0].text`, async () => {
            mocks.create.mockResolvedValue(okText(`${method}-result`));
            const reviewer = new Reviewer('sk-test');
            const result = await (reviewer as any)[method]('code');

            expect(result).toBe(`${method}-result`);
            expect(mocks.create).toHaveBeenCalledTimes(1);
        });
    }
});

describe('error handling', () => {
    it('submitCode wraps client errors with an OpenAI API error prefix', async () => {
        mocks.create.mockRejectedValue(new Error('boom'));
        await expect(new Reviewer('sk-test').submitCode('code')).rejects.toThrow(
            'OpenAI API error: boom',
        );
    });

    it('getCurrentModels wraps client errors', async () => {
        mocks.get.mockRejectedValue(new Error('unauthorized'));
        await expect(new Reviewer('sk-test').getCurrentModels()).rejects.toThrow(
            'OpenAI API error: unauthorized',
        );
    });
});
