// https://platform.openai.com/docs/deprecations
import OpenAI from 'openai';
import {exec} from 'child_process';
import {
    generateCodeStyleRecommendationsPrompt,
    generateDocumentationPrompt, generateHistoricalAnalysisPrompt,
    generateOptimizeCodePrompt,
    generateSecurityAnalysisPrompt,
    generateSubmitCodeAssistanceModePrompt,
    generateSubmitCodePrompt,
    generateTestsPrompt,
    SYSTEM_PROMPT
} from "./utils/prompts";
import { defaultOptions } from './utils/default-options';

interface IModel {
    id: string;
    object: string;
    created: number;
    owned_by: string;
}

interface IDefaultOptions  {
    temperature: number;
    top_p: number;
    frequency_penalty: number;
    presence_penalty: number;
    n: number;
    stop?: string[];
}


class Reviewer {
    private readonly apiKey;
    private readonly model;
    private readonly client;
    private readonly maxTokens;
    private readonly modelOptions;

    constructor(apiKey: string, model = 'gpt-4o-mini', maxTokens = 1500, defaultClassOptions: IDefaultOptions = defaultOptions) {
        this.apiKey = apiKey;
        this.model = model;
        this.maxTokens = maxTokens;
        this.modelOptions = defaultClassOptions

        this.client = new OpenAI({
            apiKey: this.apiKey,
        });
    }

    // True for legacy text-completion models (e.g. gpt-3.5-turbo-instruct), which
    // must go through the old Completions API rather than Chat Completions.
    private isInstruct(): boolean {
        return this.model.endsWith('-instruct');
    }

    // Single entry point for every prompt. Routes to Chat Completions by default and
    // falls back to the legacy Completions API for instruct models, so callers that
    // still pass an instruct model keep working. Returns the model's text output.
    private async complete(userPrompt: string, overrides: Record<string, any> = {}): Promise<string> {
        try {
            if (this.isInstruct()) {
                const response: any = await this.client.completions.create({
                    model: this.model,
                    prompt: userPrompt,
                    max_tokens: this.maxTokens,
                    ...this.modelOptions,
                    ...overrides,
                });
                return response.choices[0]?.text ?? '';
            }

            // Reasoning models (o1/o3/…) use `max_completion_tokens` and reject `temperature`/`top_p`.
            const isReasoning = /^o\d/.test(this.model);
            const { temperature, top_p, ...reasoningSafeOptions } = this.modelOptions;
            const response = await this.client.chat.completions.create({
                model: this.model,
                messages: [
                    { role: 'system' as const, content: SYSTEM_PROMPT },
                    { role: 'user' as const, content: userPrompt },
                ],
                ...(isReasoning
                    ? { max_completion_tokens: this.maxTokens, ...reasoningSafeOptions }
                    : { max_tokens: this.maxTokens, ...this.modelOptions }),
                ...overrides,
            });
            return response.choices[0]?.message?.content ?? '';
        } catch (error: any) {
            throw new Error(`OpenAI API error: ${error?.message || error}`);
        }
    }

    async submitCode(code: string): Promise<string | undefined> {
        return this.complete(generateSubmitCodePrompt(code));
    }

    async submitCodeAssistanceMode(code: string): Promise<string | undefined> {
        return this.complete(generateSubmitCodeAssistanceModePrompt(code));
    }

    async getCurrentModels(): Promise<IModel[]> {
        try {
            const {data}: { data: IModel[] } = await this.client.get('/models');
            return data;
        } catch (error: Error | any) {
            throw new Error(`OpenAI API error: ${error.message}`);
        }
    }

    async codeReviewOnCI() {
        exec(`
            git fetch origin
            git diff origin/develop -- . ':!package-lock.json' ':!tsconfig.json' ':!dist/' > pr.diff
        `, async (err, stdout, stderr) => {
            if (err) {
                console.error(`Error executing git diff: ${stderr}`);
                return new Error(String(err));
            }

            const feedback = await this.submitCode(stdout);
            console.info('Code Review-ci Feedback:', feedback);
            return feedback;
        });
    }

    async generateDocumentation(code: string): Promise<string> {
        const content = await this.complete(generateDocumentationPrompt(code), {
            temperature: 0.5,
            n: 1,
            stop: ["*/"],
        });

        if (!content) {
            return 'No documentation generated by OpenAI API';
        }

        let documentation = content;
        if (!documentation.startsWith('/**')) {
            documentation = `/**\n${documentation}`;
        }
        if (!documentation.endsWith('*/')) {
            documentation = `${documentation}\n*/`;
        }
        return documentation;
    }

    async optimizeCode(code: string): Promise<string> {
        return this.complete(generateOptimizeCodePrompt(code));
    }

    async generateTests(code: string): Promise<string> {
        return this.complete(generateTestsPrompt(code), { temperature: 0.5, n: 1 });
    }

    async securityAnalysis(code: string): Promise<string> {
        return this.complete(generateSecurityAnalysisPrompt(code));
    }

    async codeStyleRecommendations(code: string): Promise<string> {
        return this.complete(generateCodeStyleRecommendationsPrompt(code), { temperature: 0.5, n: 1 });
    }

    async historicalAnalysis(repoPathOrDiff: string): Promise<string> {
        return this.complete(generateHistoricalAnalysisPrompt(repoPathOrDiff), { temperature: 0.5, n: 1 });
    }
}

export {
    Reviewer
};
