name: Deploy to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Publish to npm
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        run:  |
          npm ci
          npm publish publish:package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
