name: Check build ability

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check_build_ability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run code
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm run build && npm run build:util
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} node ./dist/init-lib-helper.js > review_feedback.txt
          REVIEW_FEEDBACK=$(cat review_feedback.txt)
          echo $REVIEW_FEEDBACK
